/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Post blog": "发布博客",
    "Title": "标题",
    "Welcome to CSS Clicker!": "欢迎来到 Css点击器！",
    "Upgrades": "升级",
    "Upgrades Store": "升级商店",
    "views on your website": "您网站的浏览次数",
    "Why build a game in CSS?": "为什么要用CSS制作游戏？",
    "why does this site use so much javascript": "为什么这个网站用了这么多javascript",
    "Why is it called CSS Clicker?": "为什么它叫 Css点击器？",
    "The blog is pretty informative.": "这个博客内容丰富。",
    "The end?": "终点?",
    "Theme color": "主题颜色",
    "THIS SITE IS SO COOL": "这个网站太酷了",
    "Told you so! ^_^": "早告诉过你了！^ _ ^",
    "Website design": "网站设计",
    "work in progress (click to ed": "作品进行中 (点击编辑",
    ", should you prefer to look at it there.": "，如果你想在那里看的话。",
    "(plays with audio)": "（同时播放音频）",
    "Animate the views counter": "动画视图计数器",
    "background:": "背景:",
    "Badges": "徽章",
    "Basic HTML": "基础 HTML",
    "Click on the badges to toggle them.": "点击徽章来切换它们。",
    "Click here": "点击这里",
    "click here": "点击这里",
    "Check out what you bought": "看看你买了什么",
    "Check these tabs to use them on your site.": "检查这些标签以在您的网站上使用它们。",
    "Contact button": "联系按钮",
    "Contact Us": "联系我们",
    "Content": "内容",
    "Credits": "鸣谢",
    "CSS Clicker": "CSS点击器",
    "CSS Clicker is an idle game themed around making websites.": "CSS点击器 是一款以制作网站为主题的放置游戏。",
    "CSS Clicker is an incremental game themed around making websites.": "CSS Clicker是一款以制作网站为主题的增量游戏。",
    "color": "颜色",
    "Collapse": "折叠",
    "Other Settings": "其他设置",
    "Page Elements": "页面元素",
    "Pick a cursor to use for your website.": "为你的网站选择一个光标。",
    "pro tip: press ctrl+p": "专业提示：按ctrl+p",
    "Proud of what you've made? Please do share your works of art, and tag me so I can see them too:": "为你的成就感到骄傲？请分享你的艺术作品，并@我，这样我也能看到它们：",
    "Ready to say goodbye?": "准备好说再见了吗？",
    "Refresh the page if you're on desktop or didn't click/tap to start the intro yet. TODO: try setting focus attribute on a random element hopefully it'll fix mobile refresh": "刷新页面，如果你在桌面上或没有点击/点击开始介绍。待办事项：尝试在随机元素上设置焦点属性，希望它能修复手机刷新",
    "START GAME": "开始游戏",
    "Surprisingly, yes!": "令人惊讶的是，是的！",
    "Untitled Section": "无标题的部分",
    "Your goal is to make your own website and level it up by buying all sorts of upgrades for your site in the pursuit of becoming the most famous website on the interwebs.": "你的目标是建立自己的网站，并通过购买各种升级来升级你的网站，以追求成为互联网上最著名的网站。",
    "Your progress": "你的进度",
    "Your goal is to build a website and level it up by buying all sorts of upgrades for your site": "你的目标是建立一个网站，并通过购买各种升级来升级你的网站",
    "You've used up all your blogposts!": "你的博客文章都写完了！",
    "This is the coolest website of all time!!": "这是有史以来最酷的网站！！",
    "This site was developed on Chrome versions 134-136 and Firefox version 136. It should work pretty well in those browsers. Other browsers may encounter weird issues, sorry.": "本网站是在Chrome版本134-136和Firefox版本136上开发的。它应该在这些浏览器中工作得很好。其他浏览器可能会遇到奇怪的问题，抱歉。",
    "This entire game is written in HTML and CSS. No JavaScript or server-side code is used :).": "整个游戏是用HTML和CSS编写的。没有使用JavaScript或服务器端代码：)。",
    "It's a \"fuck you\" to people claiming HTML/CSS aren't programming languages.": "对于那些声称HTML/CSS不是编程语言的人来说，这是一种“”。",
    "in the pursuit of becoming the most famous website on the interwebs.": "为了成为互联网上最著名的网站。",
    "{ Click to start }": "{ 点击开始 }",
    "MUSIC": "音乐",
    "music:": "音乐:",
    "Mute currently playing audio": "静音当前播放的音频",
    "an incremental game by rebane2001": "rebane2001的增量游戏",
    "MySpace:": "我的空间:",
    "My Cool Website": "Git游戏",
    "Material": "Material",
    "It's definitely a game intended for desktop browsers, and I wouldn't recommend playing on mobile, but I've added a few tweaks to make it playable on Android phones running Chrome or Firefox. I have not been able to test it on Safari (neither desktop nor mobile), so ymmw there.": "这绝对是一款面向桌面浏览器的游戏，我并不建议玩家在手机上玩它，但我也做了一些调整，让它能够在运行Chrome或Firefox的Android手机上玩。我没能在Safari上测试它（桌面和手机都没有），所以我没办法。",
    "HTML/CSS aren't programming languages": "HTML/CSS不是编程语言",
    "rebane presents": "反弹演示文稿",
    "About": "关于",
    "Accent color": "强调色",
    "Background photos by me ^^.": "背景照片是我拍的^^。",
    "be lost.": "迷失自我。",
    "Blackle Mori": "Blackle Mori",
    "a small screen": "一个小屏幕",
    "a no-js game": "一个没有js的游戏",
    "a video": "一个视频",
    "add me on planetminecraft": "在 planetminecraft 上添加我",
    "about that! But the projects I made there were still very much just fun toys and tech demos. I wanted to make something in CSS that felt like a fully featured game, and this project is me doing that.": "关于这个的问题!但我在那里做的项目仍然只是有趣的玩具和技术演示。我想用CSS做一些东西，感觉就像一个功能齐全的游戏，这个项目就是我在做的。",
    "Make it your own": "让它成为你自己的",
    "Blog": "博客",
    "E-mail:": "邮箱:",
    "Enable monitor glow": "启用显示器发光",
    "Enable Winamp": "启用Winamp",
    "Endgame": "终局",
    "Firefox stores the state of input elements, you can press ctrl+shift+r to refresh without this behaviour.": "Firefox存储输入元素的状态，您可以按ctrl+shift+r来刷新，而不需要此行为。",
    "Guestbook": "留言簿",
    "Google Plus:": "谷歌+:",
    "You can start earning views by refreshing your own website.": "你可以通过刷新自己的网站来获得浏览量。",
    "You can also press ctrl+p to save a high-quality PDF of your website! (don't forget to enable \"Background graphics\" in print settings)": "您也可以按ctrl+p保存您的网站的高质量的PDF ！（不要忘记在打印设置中启用“背景图形”）",
    "You can use design systems to completely overhaul your site, check it out here.": "你可以使用设计系统来彻底检查你的网站，看看这里。",
    "You can't, sorry >w<.": "你不能，抱歉>w<。",
    "You must write more to post...": "你必须写更多的文章…",
    "You will unlock more of these later.": "稍后您将解锁更多内容。",
    "You've bought the final endgame upgrade - Geocities - and thus the clicker part of the game is sort of over now. But fear not, for this upgrade gives you a lot of awesome customization options to play around with, check them out in the": "你已经购买了最后的游戏升级-地理城市-因此游戏的点击部分现在已经结束了。但是不要害怕，因为这次升级给了你很多很棒的自定义选项来玩，看看他们在",
    "You've unlocked badges!": "你已经解锁了徽章！",
    "copyright is no": "© copyright gityx.com",
    "Could you add my button to yr site too 🥺": "你能把我的按钮也添加到你的网站🥺吗",
    "CSS crimes": "CSS crimes",
    "Cursors, GIFs, and 88x31 badges from various sources, mostly": "主要是各种来源的光标、动图和88x31徽章",
    "Cursors": "光标",
    "Design": "设计",
    "Custom cursors": "自定义光标",
    "Design systems": "设计系统",
    "Design systems unlocked!": "设计系统已解锁",
    "Expand": "展开",
    "First section": "第一部分",
    "first!!": "第一! !",
    "fuck you": "我爱你",
    "Hello! boss! I have a memecoin project , can we cooperate?": "你好!老板!我有一个memecoin项目，我们可以合作吗？",
    "Clicker": "点击器",
    "Contact": "联系",
    "Performance": "性能",
    "Shows cursors on the Clicker screen": "在“点击器”屏幕上显示光标",
    "Thank you to all the cohost CSS crimes people (especially": "感谢所有的合作主办CSS crimes的人 (特别是",
    "The screen can get a little cramped, so use the collapse button if necessary.": "屏幕可能会有点狭窄，所以必要时使用折叠按钮。",
    "The site is yours to customize, add your own text and make it feel like you.": "这个网站是你自定义的，添加你自己的文字，让它感觉像你。",
    "This game was written entirely in HTML/CSS and uses no javascript or server-side code. No, seriously, you can disable JavaScript in your browser and the game remains fully functional.": "这款游戏完全是用HTML/CSS编写的，没有使用javascript或服务器端代码。不，说真的，你可以在浏览器中禁用JavaScript，游戏仍然可以正常运行。",
    "through Cohost. It was a social media platform that allowed limited HTML and inline CSS in its posts, and people made some amazing stuff with it. I even made": "通过Cohost。它是一个社交媒体平台，允许在帖子中使用有限的HTML和内联CSS，人们用它制作了一些惊人的东西。我甚至做了",
    "When you buy upgrades, you also unlock new customization options.": "当你购买升级时，你也可以解锁新的自定义选项。",
    "Wait, how do you know I have JS disabled?": "等等，你怎么知道我有JS障碍？",
    "Yes, I am.": "是的，我是。",
    "You can also press ctrl+p to save a high-quality PDF of it!": "你也可以按ctrl+p保存一个高质量的PDF文件！",
    "Huh... it really does work with JavaScript disabled.": "嗯……它确实可以在禁用JavaScript的情况下工作。",
    "Hi, are you interested in selling your domain?": "您好，您有兴趣出售您的域名吗？",
    "How do I save progress?": "我如何保存进度？",
    "How can I share my website?": "我如何分享我的网站？",
    "Home": "首页",
    "Intro paragraph": "介绍段落",
    "Does this game work on mobile?": "这款游戏是否适用于手机平台？",
    "Don't forget to enable \"Background graphics\" in print settings if you do that.": "如果你这样做的话，不要忘记在打印设置中启用“背景图形”。",
    "Do not close or refresh the tab, or you'll have to start from the beginning.": "不要关闭或刷新选项卡，否则您将不得不从头开始。",
    ") for inspiring me and getting me into writing my own CSS crimes! <3": ")，感谢你启发了我，让我开始编写自己的CSS crime ！＜3",
    "Second section": "第二部分",
    "Playing on": "进行游戏在",
    "Does this game really not use any JavaScript?": "这款游戏真的不使用任何JavaScript吗？",
    "Questions I think people are gonna be asking frequently": "我认为人们会经常问这些问题",
    "I refreshed the page and now things seem weird?": "我刷新了页面，现在看起来很奇怪？",
    "Take a screenshot and send it my way on": "截个截图发给我在",
    "Or send me an e-mail at lyra.horse+css [at] gmail.com.": "或者给我发邮件在lyra上。Horse +css [at] gmail.com。",
    "Mhm! Go ahead, turn off JavaScript in the site settings and see for yourself.": "嗯!继续，在站点设置中关闭JavaScript，自己看看。",
    "It's a fun technical challenge!": "这是一个有趣的技术挑战！",
    "I first got into  making": "我第一次接触制作",
    "as it's often done to downvalue certain groups of people. There is nuance to this, maybe I'll write a blogpost about it some day.": "因为它经常贬低某些群体的价值。这是有细微差别的，也许有一天我会写一篇关于它的博文。",
    "Also, I hate it when people insist that": "而且，我讨厌人们坚持这样做",
    "I want to make my own website for real now, can I take ideas/assets from here?": "我想让我自己的网站真正现在，我可以从这里采取的想法/资产？",
    "Yes.": "是的.",
    "More sites should have guestbooks": "更多的网站应该有留言簿",
    "Most of the code in this project was handwritten (no preprocessors), so the source code can be seen by just right clicking the page and clicking \"view source\". This also means you can ctrl+s save this site offline. The source code is also available on": "这个项目中的大部分代码都是手写的（没有预处理器），因此只需右键单击页面并单击“查看源代码”就可以看到源代码。这也意味着您可以按ctrl+s保存该站点脱机。源代码也可在",
    "it text)": "文本)",
    "(default)": "(默认)",
    "(converted to animated GIFs).": "（转换为gif动画图片）。",
    "(100% not reached)": "（100%未达到）",
    "I'd love to see what you come up with!": "我很想看看你能想出什么！",
    "I mean, you're playing it on mobile as we speak.": "我的意思是，就在我们说话的时候，你们正在手机上玩这款游戏。",
    "I am a cool person, hi!": "我是一个很酷的人，嗨！",
    "If you're 100% sure you're done with everything in the game and want an ending,": "如果你100%确定你已经完成了游戏中的所有内容，想要一个结局，",
    "If you're seeing this screen, then either you're on mobile or there was a problem loading the page or starting the intro animation.": "如果你看到的是这个屏幕，那么你要么是在使用手机，要么是在加载页面或开始介绍动画时遇到了问题。",
    "Intro music is": "介绍音乐是",
    "my final message goodbye": "我最后的留言是再见",
    "omg this site reminds me of internet explorer 6": "天哪，这个网站让我想起了ie6",
    "Original oneko art from": "原创oneko艺术来自",
    "Playtested by": "游戏测试由",
    "tab and make your website your own.": "标签并使您的网站成为您自己的。",
    "Add them to your site here.": "将它们添加到您的网站。",
    "best viewed in netscape navigator": "最好在网景导航浏览",
    "from the emptiness, something new": "从空虚中，得到新的东西",
    "Tap this screen to bypass it.": "点击这个屏幕可以绕过它。",
    "the little kitty is soo cute!": "小猫咪太可爱了！",
    "i love your taste of music!": "我喜欢你的音乐品味！",
    "I love your site so much!": "我非常喜欢你的网站！",
    "i wish i had skills like you...": "我希望我有你这样的技能……",
    "i love ur writing!!": "我喜欢你的作品！！",
    "Share the site with your friends:": "与你的朋友分享这个网站：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Cohost:": "Cohost:",
    "Skype:": "Skype:",
    "content": "content",
    "mobile": "手机",
    "right": "right",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Create a new blogpost ": "创建一篇新的博客文章 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "views] Custom Cursors I (multiple)": "浏览] 自定义光标 I（多个）",
    "views] Custom Cursors II (multiple)": "浏览] 自定义光标 II（多个）",
    "views] Section": "浏览] 部分",
    "views] Gaming Mouse": "浏览] 游戏鼠标",
    "views] Design system: Bootstrap": "浏览] 设计系统: Bootstrap",
    "views] Design system: Geocities": "浏览] 设计系统: Geocities",
    "views] Design system: Material": "浏览] 设计系统: Material",
    "views] Design system: Tailwind": "浏览] 设计系统: Tailwind",
    "views] Blog": "浏览] 博客",
    "views] Contact": "浏览] 联系",
    "views] Guestbook": "浏览] 留言簿",
    "views] Botnet": "浏览] 僵尸网络",
    "views] oneko": "浏览] oneko",
    "views] Winamp": "浏览] Winamp",
    "views] 88x31 Badge (multiple)": "浏览] 88x31 徽章 (多个)",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Blog storage quota: (.+) posts used.$/, '博客存储配额：已使用 $1 篇文章。'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);